### PR TITLE
Website: Mobile and desktop have it's own search input

### LINKED ISSUE #857: 📎 Make better icons for mobile topbar
- [x] show a close icon when the menu or TOC is open on mobile

Current: 
Annotation 2020-07-20 002545

Others interations:
Annotation 2020-07-19 214838
Annotation 2020-07-19 214934
Annotation 2020-07-19 225536
Annotation 2020-07-19 225635
Annotation 2020-07-19 231510

### PR DESCRIPTION
**Pull request by EduardoLopes**
## Summary

This PR closes #857.

Mobile and desktop have it's own search input. The mobile search input is on the same sidebar as the toc, while on desktop it's on the navigation sidebar.

`docsearch` will act on the input based on the window size. This means if the window size changed below or over the mobile breakpoint (768) on runtime, one of the inputs will not work.

- [x] Add a media query event listener and instantiate docsearch for that platform
- [x] TOC sidebar should be rendered on every page
  - [x] When there's no TOC, only shows on mobile
- [x] Hamburger icon match the magnifying glass icon
- [x] Show close icon when a mobile menus is open

### CODE REVIEW

**Comment by EduardoLopes** [comment]
@sebmck  check it out

**Comment by sebmck** [comment]
Ohh nice! I like it! It's broken on the homepage though (and any page without a TOC) since in `base.njk` we only output the sidebar if there's a TOC. the `{% if tocHTML != "" %}` condition can be moved to just cover the `nav` though.

**Comment by EduardoLopes** [comment]
This is finished. I was thinking about make the menus come from the top, but i think it looks ok like this. what do you think?

(feel free to merge it, if you think it's good)

**Comment by sebmck** [comment]
Ohhh, looks great!

**Pull request merged**
