### PR TITLE
docs: anchor-has-content.md

### PR DESCRIPTION
**Pull request by ematipico**
I guess we should start writing some documentation. Here's a first a PR. Maybe we should come up with a structure of the page:

```
# <rule name>

Description

## Invalid

## Valid

## Accessibility resources (if applicable)

## Resource (if applicable)

```

I followed more or less the upstream plugin

### CODE REVIEW

**Comment by VictorHom** [comment]
Good call on getting documentation ready for the release 🎉 

What are your thoughts on using the test cases for rules as the Valid and Invalid cases in the doc?

**Comment by sebmck** [comment]
> What are your thoughts on using the test cases for rules as the Valid and Invalid cases in the doc?

Ohhh this would be so good. I wonder if there's an easy way we can do this.

Easiest way will be to move the `valid`/`invalid` test cases into a `json` file. That might actually be nice? We can eliminate a lot of the test files that are just a bunch of boilerplate for a `testLint` call.

Maybe something like:

```
{
  "lint-rule-name": {
    "valid": [],
    "invalid": [],
  },
}
```

That we can have in `packages/@romejs/compiler/lint/rules/tests.json`. Then we can have `packages/@romejs/compiler/lint/rules/index.test.ts` that just imports it and sets up the tests. Then we can generate a lot of the lint docs.

**Comment by sebmck** [comment]
Opened #728 to track!

**Comment by bitpshr** [comment]
@ematipico should we close this for now in favor of a new PR following the approach described in #728?

**Comment by ematipico** [comment]
@bitpshr it makes totally sense!

**Pull request closed without merging**
