### PR TITLE
Website: Improve breadcrumbs style

### PR DESCRIPTION
**Pull request by EduardoLopes**
This PR improves breadcrumbs style, here's how it looks:

breadcrumbs-2

It's scrollable on mobile:
breadcrumbs-1

### CODE REVIEW

**Comment by sebmck** [comment]
Nice! The contrast of the hover states isn't very strong, I only noticed it because I was specifically looking for it. Both in light and dark mode. Could we make it darker in light mode and lighter in dark mode?

**Comment by EduardoLopes** [comment]
check it out now

**Comment by EduardoLopes** [comment]
wait

**Comment by EduardoLopes** [comment]
done

**Comment by sebmck** [comment]
Thank you!

**Pull request merged**
