### PR TITLE
Feature/add documentation to missing rules

### LINKED ISSUE #939: 📎 [docs] add description to our rules
At the moment our rules page (https://romefrontend.dev/docs/lint/rules/?veryfunny) is quite empty and we should make an effort to put some documentation.

How to help:
- open a rule file (e.g. `preferInterfaces.md`)
- update the `description: MISSING DOCUMENTATION` part. This will update the brief description inside the main rules page
- update the `MISSING DOCUMENTATION` under the name of the rule with some meaningful description; alternately we can have a link to the upstream rule at the moment. We don't need some fancy stuff I think :)
- run the command `./rome run scripts/generate-all-files.ts` and commit everything

I will start with some PR

### PR DESCRIPTION
**Pull request by katungi**
## Summary

This PR fills in the missing documentation on the rules part.

This PR closes #939 
## Test Plan
Ran the command ``./rome run scripts/generate-all-files.ts ``

### CODE REVIEW

**Comment by sebmck** [comment]
Thank you! Looks like the `.vscode` directory was added by mistake.

**Comment by katungi** [comment]
Hey @sebmck I will gitignore it asap. Thanks for that!

**Comment by JustBeYou** [comment]
@katungi I think you should squash your commits or reset them and recommit. Adding and then deleting the `.vscode` directory should not appear in history as it is not relevant. 

PS. I'm not a contributor to this project yet, just stalking around, but I hope it helps 😄

**Comment by sebmck** [comment]
@JustBeYou All PRs are squashed when merging so it doesn't matter!

@katungi Thanks! I have some nits but will fix them separately myself since we're under a bit of a time crunch of release in a few hours.

**Pull request merged**
