### PR TITLE
Added fetch forks information functionality for Credits / Fork section

### PR DESCRIPTION
**Pull request by arneesh**
## Summary

Added Fetch forks information functionality for the Credits / Fork section of the website.

### CODE REVIEW

**Comment by sebmck** [comment]
Thanks for the PR! This isn't actually what I had in mind for the credits section. It's about the code inside of Rome that we have forked from other projects. Right now we have 328 forks and only 77 contributors so it's not an accurate display of actual project credit to list repo forks.

**Comment by arneesh** [comment]
> Thanks for the PR! This isn't actually what I had in mind for the credits section. It's about the code inside of Rome that we have forked from other projects. Right now we have 328 forks and only 77 contributors so it's not an accurate display of actual project credit to list repo forks.

We can get the contributors by just replacing the last word in the API  from '/forks' to '/contributors'
`const options = {
	host: "api.github.com",
	path: "/repos/romefrontend/rome/contributors",
	headers: {"User-Agent": "romefrontend/rome"},
};`

But yes, like you said you were thinking about adding the repos that have been forked inside Rome instead of this then of course this code won't be useful.

**Comment by sebmck** [comment]
Ahh sorry @arneesh, I accidentally closed this by referring to the wrong PR. I'm currently working on the credits section and if you don't mind I can take what you've done here and implement it to show only those with committed code.

**Comment by arneesh** [comment]
> Ahh sorry @arneesh, I accidentally closed this by referring to the wrong PR. I'm currently working on the credits section and if you don't mind I can take what you've done here and implement it to show only those with committed code.

Yes of course. No problem.

**Pull request closed without merging**
