### PR TITLE
Move website to a single page

### PR DESCRIPTION
**Pull request by sebmck**
This PR is a work in progress. View the Netlify deploy to see. The copy is still extremely rough. I only merged all the pages last night and I stopped writing a lot of the docs mid-sentence so only looking for feedback on the overall structure right now. I also have no tested a lot on mobile so there could be some bugs there.

In the process of trying to figure out all the different doc pages, it was really hard to decide what goes on which page. Originally we wanted to have everything on a single page that didn't seem practical. I think it actually is! The only separate pages we need are for lint rules which can be overly verbose and include examples etc.

This places an extreme emphasis on the Table of Contents, which unfortunately means removing some of our existing UI elements that are no longer necessary. The left sidebar now consists only of a few links at the top and the table of contents below. We still have the search input to allow searching other lint rules.

The getting started button is also gone because we jump straight into the Getting Started.

I'm sad because this undoes some of the recent work by @EduardoLopes, notably having a dedicated sidebar for the search on mobile, which isn't necessary now since they're one.

I don't have a lot of strong opinions on the layout, other than how we can make it most effectively work with a single page.

### CODE REVIEW

**Comment by ematipico** [comment]
The search on mobile doesn't work.

Clicking on the lens makes the website unresponsive (can't scroll) unless the X icon is clicked or the menu icon is clicked.

**Comment by sebmck** [comment]
Pushed my latest changes.

> The social icons should be moved to the end of the page.

What do you mean? The ones below the lint output preview?

**Comment by ematipico** [comment]
> What do you mean? The ones below the lint output preview?


Yes, open collective, GitHub and Twitter icons. Usually they are at the end of the page unless you wanted to have them there on purpose.

**Comment by sebmck** [comment]
> Yes, open collective, GitHub and Twitter icons. Usually they are at the end of the page unless you wanted to have them there on purpose.

Ah yeah. They're under the preview since it's close to the top and the flow of the page is someone discovering Rome for the first time, figuring out what it is, where they can learn more about it and follow, and then how to use it. We also have them in the footer too. The homepage is going to be big and so I don't imagine many people will even reach the footer and will focus on the top of the page.

**Pull request merged**
